spring:
  application:
    name: order

  datasource:
    url: jdbc:postgresql://${POSTGRE_HOST}:5432/order_db
    username: ${POSTGRE_USER}
    password: ${POSTGRE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: ${RABBITMQ_DEFAULT_HOST}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    virtual-host: ${RABBITMQ_DEFAULT_VHOST}

server:
  servlet:
    context-path: /order
  port: 8080

