spring:
  application:
    name: order

  data:
    mongodb:
      host: ${MONGO_HOST}
      port: 27017
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      database: order_db
      authentication-database: admin

  rabbitmq:
    host: ${RABBITMQ_DEFAULT_HOST}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    virtual-host: ${RABBITMQ_DEFAULT_VHOST}

server:
  servlet:
    context-path: /order
  port: 8080

